#!/usr/bin/env bash
# shellcheck disable=SC1090,SC2155
set -o errexit
set -o nounset
set -o pipefail
[[ -n "${XTRACE+x}" ]] && set -o xtrace


ITMZ_DIR=${ITMZ_DIR:-/Users/adoyle/Doc/My-Knowledge}
ITMZ_HOME=${ITMZ_HOME:-~/itmz}
ITMZ_REF_DIR=$ITMZ_HOME/refs
ITMZ_LOG=$ITMZ_HOME/itmz.log
APP_NAME=itm

run() {
  local dir=${1:-}
  local search_dir=$(realpath "$ITMZ_DIR"/"$dir")
  local target_dir="$ITMZ_REF_DIR"/"$search_dir"

  if [[ -z "$target_dir" ]]; then
    echo "itmz cache directory is empty" >&2
    exit 1
  fi

  if [[ "$target_dir" == '/' ]] || [[ "$target_dir" == "$HOME" ]]; then
    echo "Dangerous! You cannot remove the files in $target_dir" >&2
    exit 1
  fi

  read -rp "To clean cache at directory: $target_dir ? (y/n [default yes])" answer
  case $answer in
    Y|y|Yes|yes|YES)
      echo Yes
      answer=yes
      ;;
    N|n|No|no|NO)
      echo "No"
      answer=no
      ;;
    *)
      echo Yes
      answer=yes
      ;;
  esac

  if [[ $answer == yes ]]; then
    rm -rf "${target_dir:?}"/*
    echo "All cleaned"
  fi
}

run "$@"
