#!/usr/bin/env bash
# shellcheck disable=SC1090,SC2155
set -o errexit
set -o nounset
set -o pipefail
[[ -n "${TRACE+x}" ]] && set -o xtrace

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

source "$SCRIPT_DIR"/env.bash

get_available_dirs() {
  local dirs=($(find "$ITMZ_DIR" -not -name '\.*' -and -type d -depth 1 -exec basename {} \;))
  dirs+=(.)
  echo "${dirs[@]}"
}

usage() {
cat <<EOF
Usage: $0 [Options] <pattern> [dir]

Options:
    -h --help               Show help
    -l --list-file          Only list filepaths which matched

Parameters:
    <pattern>               Recursively search for PATTERN in <dir>.
    [dir]                   Default to \$ITMZ_DIR, which current is $ITMZ_DIR
                            See <Available Directories> in below.

Available Directories:
    $(get_available_dirs)
EOF
}

usage
